# Generated by Django 4.0.5 on 2022-07-23 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('FIO_coach', models.CharField(db_index=True, max_length=100, verbose_name='ФИО тренера')),
            ],
            options={
                'verbose_name': 'тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_section', models.CharField(max_length=50, verbose_name='Название секции')),
                ('idgroup', models.IntegerField(db_index=True, verbose_name='Номер группы')),
                ('quantity_in_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Кол-во занятий/неделя')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Стоимость')),
                ('FIO_coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='useris.treners', verbose_name='ФИО тренера')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=50, verbose_name='Отчество')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Возраст')),
                ('height', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(230)], verbose_name='Рост')),
                ('weight', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(150)], verbose_name='Вес')),
                ('payment', models.BooleanField(default=False, verbose_name='Оплата')),
                ('idgroup', models.ManyToManyField(to='useris.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'ребёнок',
                'verbose_name_plural': 'Дети',
            },
        ),
    ]
