# Generated by Django 4.0.5 on 2022-07-23 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useris', '0002_season_tickets_remove_children_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='children',
            name='season_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='useris.season_tickets', verbose_name='Абонемент'),
        ),
        migrations.AlterField(
            model_name='season_tickets',
            name='season_ticket',
            field=models.IntegerField(verbose_name='Абонемент'),
        ),
    ]
