# Generated by Django 4.0.5 on 2022-07-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useris', '0003_alter_children_comments_alter_children_season_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='trener',
            field=models.ManyToManyField(to='useris.treners', verbose_name='Тренер'),
        ),
        migrations.AlterField(
            model_name='children',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='children',
            name='date_of_pay',
            field=models.DateField(null=True, verbose_name='Дата посл. оплаты'),
        ),
    ]
