# Generated by Django 4.0.5 on 2022-07-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useris', '0004_children_trener_alter_children_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='trener',
        ),
        migrations.AlterField(
            model_name='children',
            name='idgroup',
            field=models.ManyToManyField(db_table='sostav_groups', to='useris.groups', verbose_name='Группа'),
        ),
    ]
