# Generated by Django 4.0.5 on 2022-08-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useris', '0005_remove_children_trener_alter_children_idgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'желающий',
                'verbose_name_plural': 'Желающие',
            },
        ),
    ]
