# Generated by Django 4.0.5 on 2022-08-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useris', '0006_userss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
