# Generated by Django 4.0.5 on 2022-08-06 19:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useris', '0008_alter_userss_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Добавлено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userss',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
