# Generated by Django 4.0.5 on 2022-08-31 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('useris', '0009_userss_created_alter_userss_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userss',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
