# Generated by Django 4.0.5 on 2022-07-23 08:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season_tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_ticket', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'абонемент',
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.RemoveField(
            model_name='children',
            name='age',
        ),
        migrations.RemoveField(
            model_name='children',
            name='height',
        ),
        migrations.RemoveField(
            model_name='children',
            name='weight',
        ),
        migrations.AddField(
            model_name='children',
            name='comments',
            field=models.TextField(null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='children',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='children',
            name='date_of_pay',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата посл. оплаты'),
        ),
        migrations.AddField(
            model_name='children',
            name='season_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='useris.treners', verbose_name='Абонемент'),
        ),
    ]
